### ISSUE TITLE
Staging GFAL attribute error

### ISSUE THREAD

**Issue by tikk3r** [apmechev/GRID_LRT#10]
I tried to stage an srm manually on loui using GRID_LRT, but it crashes:

```python
> from GRID_LRT.Staging import state_all
> r = state_all.main('test.txt')
files are at sara
L412322_SAP000_SB001_uv_001.MS_79feba07.tar is NEARLINE

> from GRID_LRT.Staging import stage_all
> stage_all.main('test.txt')
files are on SARA
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "GRID_LRT/Staging/stage_all.py", line 35, in main
    return process(urls, replace_string, match)
  File "GRID_LRT/Staging/stage_all.py", line 99, in process
    gfal.gfal_set_timeout_srm(86400)
AttributeError: 'module' object has no attribute 'gfal_set_timeout_srm'
```
`test.txt` contains an SRM: `srm://srm.grid.sara.nl:8443/pnfs/grid.sara.nl/data/lofar/ops/projects/lt5_009/412322/L412322_SAP000_SB001_uv_001.MS_79feba07.tar`

**Comment by apmechev** [comment]
Fixed in Commit [94bf1b1](https://github.com/apmechev/GRID_LRT/commit/94bf1b1d8d47c89ced310ae8a521f372a23d5bc0)
